import pathlib
J = lambda parts: chr(10).join(parts)
P = pathlib.Path('scripts/generators/backend/models_generator.py')
P.parent.mkdir(parents=True, exist_ok=True)

# Column type helpers
def S(maxlen, unique=False, nullable=True, idx=False, df=None):
    p = [f'String({maxlen})']
    if not nullable: p.append('nullable=False')
    if unique: p.append('unique=True')
    if idx: p.append('index=True')
    if df: p.append(f'default={chr(34)}{df}{chr(34)}')
    return f'mapped_column({", ".join(p)})'

def FK(t):
    return f'mapped_column(UUID(as_uuid=True), ForeignKey({chr(34)}{t}.id{chr(34)}, ondelete={chr(34)}CASCADE{chr(34)}), nullable=False, index=True)'

def EC(en, default=None):
    d = f', default={en}.{default}' if default else ''
    return f'mapped_column(Enum({en}), nullable=False{d})'

def RL(model, back, cascade=None):
    c = f', cascade={chr(34)}{cascade}{chr(34)}' if cascade else ''
    return f'relationship({chr(34)}{model}{chr(34)}, back_populates={chr(34)}{back}{chr(34)}{c})'

# Model definitions as compact tuples:
# (filename, enums_list, tables_list, table_args)
# Each table: (classname, tablename, [col_tuples], [rel_tuples])
# Each col: (name, defn)
# Each rel: (name, defn)

MODELS = [
    ('user.py',
     [('UserRole', ['admin','developer','viewer','owner']),
      ('UserStatus', ['active','inactive','suspended','pending'])],
     [('User', 'users',
       [('id', 'COL_id'),
        ('email', S(255, unique=True, nullable=False, idx=True)),
        ('password_hash', S(255, nullable=False)),
        ('full_name', S(255, nullable=False)),
        ('avatar_url', S(512)),
        ('status', EC('UserStatus', 'ACTIVE')),
        ('is_superuser', 'mapped_column(Boolean, default=False)'),
        ('is_verified', 'mapped_column(Boolean, default=False)'),
        ('last_login_at', 'mapped_column(DateTime(timezone=True), nullable=True)'),
        ('deleted_at', 'COL_del'),
        ('created_at', 'COL_crt'),
        ('updated_at', 'COL_upd')],
       [('memberships', RL('OrganizationMember', 'user', 'all, delete-orphan')),
        ('teams', RL('TeamMember', 'user', 'all, delete-orphan')),
        ('notifications', RL('Notification', 'user', 'all, delete-orphan')),
        ('api_keys', RL('APIKey', 'user', 'all, delete-orphan')),
        ('oauth_tokens', RL('OAuthToken', 'user', 'all, delete-orphan')),
        ('audit_logs', RL('AuditLog', 'user', 'all, delete-orphan'))]),
      ('OrganizationMember', 'organization_members',
       [('id', 'COL_id'),
        ('organization_id', FK('organizations')),
        ('user_id', FK('users')),
        ('role', EC('UserRole', 'DEVELOPER')),
        ('joined_at', 'mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))')],
       [('organization', RL('Organization', 'members')),
        ('user', RL('User', 'memberships'))])],
     ['UniqueConstraint("organization_id", "user_id", name="uq_org_user")']),

    ('organization.py',
     [],
     [('Organization', 'organizations',
       [('id', 'COL_id'),
        ('name', S(255, nullable=False)),
        ('slug', S(255, unique=True, nullable=False, idx=True)),
        ('logo_url', S(512)),
        ('description', 'mapped_column(Text, nullable=True)'),
        ('is_active', 'mapped_column(Boolean, default=True)'),
        ('tier', S(50, df='free')),
        ('settings', 'mapped_column(JSON, default=dict)'),
        ('deleted_at', 'COL_del'),
        ('created_at', 'COL_crt'),
        ('updated_at', 'COL_upd')],
       [('members', RL('OrganizationMember', 'organization', 'all, delete-orphan')),
        ('teams', RL('Team', 'organization', 'all, delete-orphan')),
        ('projects', RL('Project', 'organization', 'all, delete-orphan')),
        ('workflows', RL('Workflow', 'organization', 'all, delete-orphan')),
        ('templates', RL('Template', 'organization', 'all, delete-orphan')),
        ('api_keys', RL('APIKey', 'organization', 'all, delete-orphan')),
        ('subscriptions', RL('Subscription', 'organization', 'all, delete-orphan')),
        ('invoices', RL('Invoice', 'organization', 'all, delete-orphan'))])],
     []),
]

# Generate the models_generator.py code
CODE = []
CODE.append('# Auto-generated by build_models_gen.py')
CODE.append('"""Models Generator - Schema-driven production SQLAlchemy model generation."""')
CODE.append('from typing import List, Optional')
CODE.append('from scripts.generators.common.writer import FileWriter')
CODE.append('')
CODE.append('J = chr(10).join')
CODE.append('')
CODE.append("Q = chr(34)  # double quote helper")
CODE.append("SQ = chr(39)  # single quote helper")
CODE.append('')
CODE.append('BASE = J([')
BASE_ITEMS = [
    '"""AutoFlow AI - SQLAlchemy model."""',
    'import uuid',
    'from datetime import datetime, timezone',
    'from typing import Any, Dict, List, Optional',
    'from sqlalchemy import Boolean, DateTime, Enum, Float, ForeignKey,',
    '    Index, Integer, JSON, String, Text, UniqueConstraint',
    'from sqlalchemy.dialects.postgresql import UUID',
    'from sqlalchemy.orm import Mapped, mapped_column, relationship',
    'from app.core.database import Base',
    'import enum',
]
for item in BASE_ITEMS:
    CODE.append(f'    {item!r},')
CODE.append('])')
CODE.append('')
CODE.append('# Column shortcuts')
CODE.append("co = {'n': 'id', 'd': 'mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)'}")
CODE.append("cc = {'n': 'created_at', 'd': 'mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))'}")
CODE.append("cu = {'n': 'updated_at', 'd': 'mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))'}")
CODE.append("cd = {'n': 'deleted_at', 'd': 'mapped_column(DateTime(timezone=True), nullable=True)'}")
CODE.append('')
CODE.append('def make_file(enums, tables, table_args=None):')
CODE.append('    parts = [BASE, ""]')
CODE.append('    for en, vals in enums:')
CODE.append('        parts.append(f"class {en}(str, enum.Enum):")')
CODE.append('        for v in vals:')
CODE.append('            parts.append(f"    {v.upper()} = {Q}{v}{Q}")')
CODE.append('        parts.append("")')
CODE.append('    for tn, tt, cols, rels in tables:')
CODE.append('        parts.append(f"class {tn}(Base):")')
CODE.append(f'        parts.append(f"    __tablename__ = {Q}{{tt}}{Q}")')
CODE.append('        if table_args:')
CODE.append('            a = ", ".join(table_args)')
CODE.append('            parts.append(f"    __table_args__ = ({a},)")')
CODE.append('        for n, d in cols:')
CODE.append('            d2 = {"COL_id": co["d"], "COL_crt": cc["d"], "COL_upd": cu["d"], "COL_del": cd["d"]}.get(d, d)')
CODE.append('            parts.append(f"    {n} = {d2}")')
CODE.append('        for n, d in rels:')
CODE.append('            parts.append(f"    {n} = {d}")')
CODE.append('        parts.append("")')
CODE.append('    return J(parts)')
CODE.append('')
CODE.append('')
CODE.append('# Model registrations')
CODE.append('MODELS = []')
CODE.append('')

for fname, enums, tables, table_args in MODELS:
    CODE.append(f'# {fname}')
    CODE.append('MODELS.append({')
    CODE.append(f'    "file": {fname!r},')
    CODE.append('    "content": make_file(')
    # Enums
    CODE.append('        enums=[')
    for en, vals in enums:
        CODE.append(f'            ({en!r}, {vals!r}),')
    CODE.append('        ],')
    # Tables
    CODE.append('        tables=[')
    for tn, tt, cols, rels in tables:
        CODE.append('            (')
        CODE.append(f'                {tn!r}, {tt!r},')
        CODE.append('                [')
        for n, d in cols:
            CODE.append(f'                    ({n!r}, {d!r}),')
        CODE.append('                ],')
        CODE.append('                [')
        for n, d in rels:
            CODE.append(f'                    ({n!r}, {d!r}),')
        CODE.append('                ],')
        CODE.append('            ),')
    CODE.append('        ],')
    # Table args
    CODE.append(f'        table_args={table_args!r},')
    CODE.append('    ),')
