/** Centralized TanStack Query cache keys. */
export const queryKeys = {
  workflows: ["workflows"] as const,
  workflow: (id: string) => ["workflows", id] as const,
  executions: ["executions"] as const,
  metrics: ["metrics"] as const,
  alerts: ["alerts"] as const,
  health: ["health"] as const,
  activity: ["activity"] as const,
  connectors: ["connectors"] as const,
  connector: (slug: string) => ["connectors", slug] as const,
  organizations: ["organizations"] as const,
  organization: (id: string) => ["organizations", id] as const,
  apiKeys: ["api-keys"] as const,
  notifications: ["notifications"] as const,
  teams: ["teams"] as const,
  users: ["users"] as const,
  subscriptions: ["subscriptions"] as const,
  planner: ["planner"] as const,
  plannerHealth: ["planner", "health"] as const,
  dashboard: ["dashboard"] as const,
  analytics: (period: string) => ["analytics", period] as const,
  apiKey: (id: string) => ["api-keys", id] as const,
  notification: (id: string) => ["notifications", id] as const,
};
