"""AutoFlow AI - Polling runner (generated from metadata).

Runs polling triggers on their configured interval, tracks last-run
checkpoints, and dispatches events with duplicate protection.
"""

import json as _json
import logging
import threading
import time
from typing import Any, Callable, Dict, List, Optional

logger = logging.getLogger(__name__)


def _stable_event_key(event: Any) -> str:
    """Stable dedup key for a polled event.

    Uses an explicitly-supplied event id when present (ids generated by
    the default factory are random per-event and useless for dedup);
    otherwise fingerprints the event type + normalized payload.
    """
    eid = getattr(event, "event_id", "") or ""
    if eid and not eid.startswith("evt-"):
        return eid
    event_type = getattr(event, "event_type", "")
    try:
        payload = _json.dumps(event.payload, sort_keys=True, default=str)
    except Exception:  # noqa: BLE001 - fall back to repr
        payload = repr(getattr(event, "payload", ""))
    return f"{event_type}:{payload}"


class PollingRunner:
    """Runs connector polling loops with checkpoint + dedup."""

    def __init__(self) -> None:
        self._last_run: Dict[str, float] = {}
        self._seen: Dict[str, set] = {}
        self._threads: List[threading.Thread] = []
        self._stop = threading.Event()
        self._lock = threading.RLock()

    def _seen_key(self, connector: str, trigger: str) -> str:
        return f"{connector}.{trigger}"

    def start(self, connector: Any, trigger: str,
              handler: Callable,
              interval_seconds: int = 60) -> None:
        """Start a polling loop for a trigger."""
        def _loop() -> None:
            while not self._stop.is_set():
                self.poll_once(connector, trigger, handler)
                time.sleep(max(interval_seconds, 1))
        thread = threading.Thread(target=_loop, daemon=True)
        thread.start()
        with self._lock:
            self._threads.append(thread)

    def poll_once(self, connector: Any, trigger: str,
                  handler: Callable) -> int:
        """Run one polling pass; returns the number of new events."""
        key = self._seen_key(connector.name, trigger)
        try:
            events = connector.poll(trigger)
        except Exception as exc:  # noqa: BLE001
            logger.warning("poll %s failed: %s", key, exc)
            return 0
        with self._lock:
            seen = self._seen.setdefault(key, set())
        dispatched = 0
        for event in events:
            dedup_key = _stable_event_key(event)
            if dedup_key in seen:
                continue
            seen.add(dedup_key)
            try:
                handler(event)
                dispatched += 1
            except Exception as exc:  # noqa: BLE001
                logger.warning("poll handler failed for %s: %s", key, exc)
        self._last_run[key] = time.time()
        return dispatched

    def last_run(self, connector: str, trigger: str) -> Optional[float]:
        return self._last_run.get(self._seen_key(connector, trigger))

    def stop(self) -> None:
        self._stop.set()
        for thread in self._threads:
            thread.join(timeout=1.0)
        self._threads.clear()
